from dataclasses import dataclass
from typing import Protocol
from collections.abc import Sequence


@dataclass(frozen=True)
class CacheSet:
    key: str
    value: str
    ex: int | None = None
    exat: int | None = None


class Cache(Protocol):
    async def get(self, key: str) -> str | None: ...
    async def set(self, key: str, value: str, *, ex: int | None = None, exat: int | None = None) -> None: ...
    async def delete(self, key: str) -> None: ...
    async def exists(self, key: str) -> bool: ...
    async def set_many(self, items: Sequence[CacheSet]) -> None: ...
    async def delete_many(self, keys: Sequence[str]) -> None: ...
    async def exists_many(self, keys: Sequence[str]) -> list[bool]: ...
