"""create indexes for owner_id

Revision ID: 1a66fbd1a60f
Revises: 86f42e962263
Create Date: 2026-05-21 19:05:19.395892

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a66fbd1a60f'
down_revision: Union[str, Sequence[str], None] = '86f42e962263'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_platforms_owner_id'), 'platforms', ['owner_id'], unique=False)
    op.create_index(op.f('ix_ships_owner_id'), 'ships', ['owner_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ships_owner_id'), table_name='ships')
    op.drop_index(op.f('ix_platforms_owner_id'), table_name='platforms')
    # ### end Alembic commands ###
