"""create journal_events table

Revision ID: 2e57f489bd99
Revises: 5faf2288a883
Create Date: 2026-09-06 08:19:07.802888

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e57f489bd99'
down_revision: Union[str, Sequence[str], None] = '5faf2288a883'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('journal_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('emitter_type', sa.Integer(), nullable=True),
    sa.Column('emitter_id', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('params', sa.JSON(), nullable=False),
    sa.Column('severity', sa.Integer(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], onupdate='NO ACTION', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_journal_events_created_at', 'journal_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_journal_events_severity'), 'journal_events', ['severity'], unique=False)
    op.create_index(op.f('ix_journal_events_is_read'), 'journal_events', ['is_read'], unique=False)
    op.create_index('ix_journal_events_user_emitter', 'journal_events', ['user_id', 'emitter_type', 'emitter_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_journal_events_user_emitter', table_name='journal_events')
    op.drop_index(op.f('ix_journal_events_is_read'), table_name='journal_events')
    op.drop_index(op.f('ix_journal_events_severity'), table_name='journal_events')
    op.drop_index('ix_journal_events_created_at', table_name='journal_events')
    op.drop_table('journal_events')
    # ### end Alembic commands ###
