"""init

Revision ID: 74681035a9d2
Revises: 
Create Date: 2026-07-12 11:10:53.254376

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74681035a9d2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sites',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('x', sa.Float(), nullable=False),
        sa.Column('y', sa.Float(), nullable=False),
        sa.Column('site_type', sa.Integer(), nullable=False),
        sa.Column('site_content', sa.Integer(), nullable=False),
        sa.Column('state', sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sites_site_content'), 'sites', ['site_content'], unique=False)
    op.create_index(op.f('ix_sites_site_type'), 'sites', ['site_type'], unique=False)

    op.create_table('users',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('name', sa.String(length=128), nullable=False),
        sa.Column('state', sa.JSON(), nullable=False),
        sa.Column('email', sa.String(length=128), nullable=False),
        sa.Column('password_hash', sa.String(length=255), nullable=True),
        sa.Column('token_version', sa.Integer(), nullable=False),
        sa.Column('is_npc', sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('email')
    )
    op.create_table('fleets',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('owner_id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=64), nullable=False),
        sa.Column('state', sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(['owner_id'], ['users.id'], onupdate='NO ACTION', ondelete='RESTRICT'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fleets_owner_id'), 'fleets', ['owner_id'], unique=False)
    
    op.create_table('platforms',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('x', sa.Float(), nullable=False),
        sa.Column('y', sa.Float(), nullable=False),
        sa.Column('state', sa.JSON(), nullable=False),
        sa.Column('owner_id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=64), nullable=False),
        sa.ForeignKeyConstraint(['owner_id'], ['users.id'], onupdate='NO ACTION', ondelete='RESTRICT'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_platforms_owner_id'), 'platforms', ['owner_id'], unique=False)
    
    op.create_table('market_orders',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('owner_id', sa.Integer(), nullable=False),
        sa.Column('platform_id', sa.Integer(), nullable=False),
        sa.Column('order_type', sa.Integer(), nullable=False),
        sa.Column('price', sa.Integer(), nullable=False),
        sa.Column('quantity', sa.Integer(), nullable=False),
        sa.Column('item_name', sa.String(length=128), nullable=False),
        sa.ForeignKeyConstraint(['owner_id'], ['users.id'], onupdate='NO ACTION', ondelete='RESTRICT'),
        sa.ForeignKeyConstraint(['platform_id'], ['platforms.id'], onupdate='NO ACTION', ondelete='RESTRICT'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_market_orders_item_name'), 'market_orders', ['item_name'], unique=False)
    op.create_index(op.f('ix_market_orders_order_type'), 'market_orders', ['order_type'], unique=False)
    op.create_index(op.f('ix_market_orders_owner_id'), 'market_orders', ['owner_id'], unique=False)
    op.create_index(op.f('ix_market_orders_platform_id'), 'market_orders', ['platform_id'], unique=False)
    op.create_index('ix_market_orders_platform_item_type_price', 'market_orders', ['platform_id', 'item_name', 'order_type', 'price'], unique=False)
    op.create_index('ix_market_orders_platform_type_price', 'market_orders', ['platform_id', 'order_type', 'price'], unique=False)
    op.create_index(op.f('ix_market_orders_price'), 'market_orders', ['price'], unique=False)
    
    op.create_table('ships',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('name', sa.String(length=64), nullable=False),
        sa.Column('state', sa.JSON(), nullable=False),
        sa.Column('fleet_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['fleet_id'], ['fleets.id'], onupdate='NO ACTION', ondelete='RESTRICT'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ships_fleet_id'), 'ships', ['fleet_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ships_fleet_id'), table_name='ships')
    op.drop_table('ships')
    
    op.drop_index(op.f('ix_market_orders_price'), table_name='market_orders')
    op.drop_index('ix_market_orders_platform_type_price', table_name='market_orders')
    op.drop_index('ix_market_orders_platform_item_type_price', table_name='market_orders')
    op.drop_index(op.f('ix_market_orders_platform_id'), table_name='market_orders')
    op.drop_index(op.f('ix_market_orders_owner_id'), table_name='market_orders')
    op.drop_index(op.f('ix_market_orders_order_type'), table_name='market_orders')
    op.drop_index(op.f('ix_market_orders_item_name'), table_name='market_orders')
    op.drop_table('market_orders')
    
    op.drop_index(op.f('ix_platforms_owner_id'), table_name='platforms')
    op.drop_table('platforms')
    
    op.drop_index(op.f('ix_fleets_owner_id'), table_name='fleets')
    op.drop_table('fleets')
    
    op.drop_table('users')
    
    op.drop_index(op.f('ix_sites_site_type'), table_name='sites')
    op.drop_index(op.f('ix_sites_site_content'), table_name='sites')
    op.drop_table('sites')
    # ### end Alembic commands ###
