"""add npc users

Revision ID: 99b0d9ca3fd6
Revises: 1a66fbd1a60f
Create Date: 2026-05-28 11:15:42.115319

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99b0d9ca3fd6'
down_revision: Union[str, Sequence[str], None] = '1a66fbd1a60f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_npc', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_npc')
    # ### end Alembic commands ###
