"""create market orders table

Revision ID: aa8b71fed4c8
Revises: 99b0d9ca3fd6
Create Date: 2026-06-14 08:10:51.481328

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa8b71fed4c8'
down_revision: Union[str, Sequence[str], None] = '99b0d9ca3fd6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('market_orders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('platform_id', sa.Integer(), nullable=False),
    sa.Column('order_type', sa.Integer(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('item_name', sa.String(length=128), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], onupdate='NO ACTION', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['platform_id'], ['platforms.id'], onupdate='NO ACTION', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_market_orders_item_name'), 'market_orders', ['item_name'], unique=False)
    op.create_index('ix_market_orders_platform_item_type_price', 'market_orders', ['platform_id', 'item_name', 'order_type', 'price'], unique=False)
    op.create_index(op.f('ix_market_orders_order_type'), 'market_orders', ['order_type'], unique=False)
    op.create_index(op.f('ix_market_orders_owner_id'), 'market_orders', ['owner_id'], unique=False)
    op.create_index(op.f('ix_market_orders_platform_id'), 'market_orders', ['platform_id'], unique=False)
    op.create_index('ix_market_orders_platform_type_price', 'market_orders', ['platform_id', 'order_type', 'price'], unique=False)
    op.create_index(op.f('ix_market_orders_price'), 'market_orders', ['price'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('market_orders')
    # ### end Alembic commands ###
