"""add owner to ships

Revision ID: baa18fb09e07
Revises: 13e3f9d3d0e2
Create Date: 2026-05-16 07:48:31.807575

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'baa18fb09e07'
down_revision: Union[str, Sequence[str], None] = '13e3f9d3d0e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ships', sa.Column('owner_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'ships', 'users', ['owner_id'], ['id'], onupdate='NO ACTION', ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ships', type_='foreignkey')
    op.drop_column('ships', 'owner_id')
    # ### end Alembic commands ###
