from typing import Protocol

from app.defs.enums import ObjectType


class AnchorPoint(Protocol):
    def get_id(self) -> int: ...
    def attach_ship(self, ship_id: int) -> None: ...
    def detach_ship(self, ship_id: int) -> None: ...
    def get_type(self) -> ObjectType: ...