from __future__ import annotations
from typing import Protocol, TYPE_CHECKING, Optional, Callable
from collections.abc import Awaitable

from app.models.market_order import MarketOrder
from app.services.market import MarketService

if TYPE_CHECKING:
    from .fleet import FleetEntity
    from .platform import PlatformEntity
    from .user import UserEntity
    from .site import SiteEntity

class World(Protocol):
    def find_fleet(self, id: int) -> Optional[FleetEntity]: ...
    def find_platform(self, id: int) -> Optional[PlatformEntity]: ...
    def find_user(self, id: int) -> Optional[UserEntity]: ...
    def find_site(self, id: int) -> Optional[SiteEntity]: ...
    def add_async_action(self, action: Callable[[], Awaitable[any]]): ...
    def get_market_service(self) -> MarketService: ...
    async def create_fleet(self, owner_id: int, x: float, y: float) -> FleetEntity: ...
    def remove_fleet(self, fleet: FleetEntity) -> None: ...
